export enum ROUTE_NAME {
  HOME_VIEW = "HOME.VIEW",
  PAYMENT_VIEW = "PAYMENT.VIEW",
  LOGIN_VIEW = "LOGIN.VIEW",
  ORDER_HISTORY_VIEW = "ORDER.HISTORY.VIEW",
  INVENTORIES_VIEW = "INVENTORIES.VIEW",
  NEW_PRODUCT_VIEW = "NEW.PRODUCT.VIEW",
  SALE_IN_PROCESS_VIEW = "SALE.IN.PROCESS.VIEW",
}
